# Generated by Django 5.2.10 on 2026-01-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_on']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id']},
        ),
    ]
